package cn.edu.bit.cs.utils;

import java.util.ArrayList;
import java.util.List;

/**
 * 提供MIME类型与文件扩展名之间的映射
 * @author JinXuLiang
 *
 */
public class MIMEUtils {
	private static List<MIMEType> mimes=null;
	static {
		mimes=new ArrayList<MIMEType>();
		mimes.add(new MIMEType(".3gp", "video/3gpp"));
		mimes.add(new MIMEType(".aab", "application/x-authoware-bin"));
		mimes.add(new MIMEType(".aam", "application/x-authoware-map"));
		mimes.add(new MIMEType(".aas", "application/x-authoware-seg"));
		mimes.add(new MIMEType(".ai", "application/postscript"));
		mimes.add(new MIMEType(".aif", "audio/x-aiff"));
		mimes.add(new MIMEType(".aifc", "audio/x-aiff"));
		mimes.add(new MIMEType(".aiff", "audio/x-aiff"));
		mimes.add(new MIMEType(".als", "audio/X-Alpha5"));
		mimes.add(new MIMEType(".amc", "application/x-mpeg"));
		mimes.add(new MIMEType(".ani", "application/octet-stream"));
		mimes.add(new MIMEType(".apk", "application/vnd.android.package-archive"));
		mimes.add(new MIMEType(".asc", "text/plain"));
		mimes.add(new MIMEType(".asd", "application/astound"));
		mimes.add(new MIMEType(".asf", "video/x-ms-asf"));
		mimes.add(new MIMEType(".asn", "application/astound"));
		mimes.add(new MIMEType(".asp", "application/x-asap"));
		mimes.add(new MIMEType(".asx", "video/x-ms-asf"));
		mimes.add(new MIMEType(".au", "audio/basic"));
		mimes.add(new MIMEType(".avb", "application/octet-stream"));
		mimes.add(new MIMEType(".avi", "video/x-msvideo"));
		mimes.add(new MIMEType(".awb", "audio/amr-wb"));
		mimes.add(new MIMEType(".bcpio", "application/x-bcpio"));
		mimes.add(new MIMEType(".bin", "application/octet-stream"));
		mimes.add(new MIMEType(".bld", "application/bld"));
		mimes.add(new MIMEType(".bld2", "application/bld2"));
		mimes.add(new MIMEType(".bmp", "application/x-MS-bmp"));
		mimes.add(new MIMEType(".bpk", "application/octet-stream"));
		mimes.add(new MIMEType(".bz2", "application/x-bzip2"));
		mimes.add(new MIMEType(".cal", "image/x-cals"));
		mimes.add(new MIMEType(".ccn", "application/x-cnc"));
		mimes.add(new MIMEType(".cco", "application/x-cocoa"));
		mimes.add(new MIMEType(".cdf", "application/x-netcdf"));
		mimes.add(new MIMEType(".cgi", "magnus-internal/cgi"));
		mimes.add(new MIMEType(".chat", "application/x-chat"));
		mimes.add(new MIMEType(".class", "application/octet-stream"));
		mimes.add(new MIMEType(".clp", "application/x-msclip"));
		mimes.add(new MIMEType(".cmx", "application/x-cmx"));
		mimes.add(new MIMEType(".co", "application/x-cult3d-object"));
		mimes.add(new MIMEType(".cod", "image/cis-cod"));
		mimes.add(new MIMEType(".cpio", "application/x-cpio"));
		mimes.add(new MIMEType(".cpt", "application/mac-compactpro"));
		mimes.add(new MIMEType(".crd", "application/x-mscardfile"));
		mimes.add(new MIMEType(".csh", "application/x-csh"));
		mimes.add(new MIMEType(".csm", "chemical/x-csml"));
		mimes.add(new MIMEType(".csml", "chemical/x-csml"));
		mimes.add(new MIMEType(".css", "text/css"));
		mimes.add(new MIMEType(".cur", "application/octet-stream"));
		mimes.add(new MIMEType(".dcm", "x-lml/x-evm"));
		mimes.add(new MIMEType(".dcr", "application/x-director"));
		mimes.add(new MIMEType(".dcx", "image/x-dcx"));
		mimes.add(new MIMEType(".dhtml", "text/html"));
		mimes.add(new MIMEType(".dir", "application/x-director"));
		mimes.add(new MIMEType(".dll", "application/octet-stream"));
		mimes.add(new MIMEType(".dmg", "application/octet-stream"));
		mimes.add(new MIMEType(".dms", "application/octet-stream"));
		mimes.add(new MIMEType(".doc", "application/msword"));
		mimes.add(new MIMEType(".dot", "application/x-dot"));
		mimes.add(new MIMEType(".dvi", "application/x-dvi"));
		mimes.add(new MIMEType(".dwf", "drawing/x-dwf"));
		mimes.add(new MIMEType(".dwg", "application/x-autocad"));
		mimes.add(new MIMEType(".dxf", "application/x-autocad"));
		mimes.add(new MIMEType(".dxr", "application/x-director"));
		mimes.add(new MIMEType(".ebk", "application/x-expandedbook"));
		mimes.add(new MIMEType(".emb", "chemical/x-embl-dl-nucleotide"));
		mimes.add(new MIMEType(".embl", "chemical/x-embl-dl-nucleotide"));
		mimes.add(new MIMEType(".eps", "application/postscript"));
		mimes.add(new MIMEType(".epub", "application/epub+zip"));
    	mimes.add(new MIMEType(".eri", "image/x-eri"));
		mimes.add(new MIMEType(".es", "audio/echospeech"));
		mimes.add(new MIMEType(".esl", "audio/echospeech"));
		mimes.add(new MIMEType(".etc", "application/x-earthtime"));
		mimes.add(new MIMEType(".etx", "text/x-setext"));
		mimes.add(new MIMEType(".evm", "x-lml/x-evm"));
		mimes.add(new MIMEType(".evy", "application/x-envoy"));
		mimes.add(new MIMEType(".exe", "application/octet-stream"));
		mimes.add(new MIMEType(".fh4", "image/x-freehand"));
		mimes.add(new MIMEType(".fh5", "image/x-freehand"));
		mimes.add(new MIMEType(".fhc", "image/x-freehand"));
		mimes.add(new MIMEType(".fif", "image/fif"));
		mimes.add(new MIMEType(".fm", "application/x-maker"));
		mimes.add(new MIMEType(".fpx", "image/x-fpx"));
		mimes.add(new MIMEType(".fvi", "video/isivideo"));
		mimes.add(new MIMEType(".gau", "chemical/x-gaussian-input"));
		mimes.add(new MIMEType(".gca", "application/x-gca-compressed"));
		mimes.add(new MIMEType(".gdb", "x-lml/x-gdb"));
		mimes.add(new MIMEType(".gif", "image/gif"));
		mimes.add(new MIMEType(".gps", "application/x-gps"));
		mimes.add(new MIMEType(".gtar", "application/x-gtar"));
		mimes.add(new MIMEType(".gz", " application/x-gzip"));
		mimes.add(new MIMEType(".hdf", "application/x-hdf"));
		mimes.add(new MIMEType(".hdm", "text/x-hdml"));
		mimes.add(new MIMEType(".hdml", "text/x-hdml"));
		mimes.add(new MIMEType(".hlp", "application/winhlp"));
		mimes.add(new MIMEType(".hqx", "application/mac-binhex40"));
		mimes.add(new MIMEType(".htm", "text/html"));
		mimes.add(new MIMEType(".html", " text/html"));
		mimes.add(new MIMEType(".hts", "text/html"));
		mimes.add(new MIMEType(".ice", "x-conference/x-cooltalk"));
		mimes.add(new MIMEType(".ico", "application/octet-stream"));
		mimes.add(new MIMEType(".ief", "image/ief"));
		mimes.add(new MIMEType(".ifm", "image/gif"));
		mimes.add(new MIMEType(".ifs", "image/ifs"));
		mimes.add(new MIMEType(".imy", "audio/melody"));
		mimes.add(new MIMEType(".ins", "application/x-NET-Install"));
		mimes.add(new MIMEType(".ips", "application/x-ipscript"));
		mimes.add(new MIMEType(".ipx", "application/x-ipix"));
		mimes.add(new MIMEType(".it", "audio/x-mod"));
		mimes.add(new MIMEType(".itz", "audio/x-mod"));
		mimes.add(new MIMEType(".ivr", "i-world/i-vrml"));
		mimes.add(new MIMEType(".j2k", "image/j2k"));
		mimes.add(new MIMEType(".jad", "text/vnd.sun.j2me.app-descriptor"));
		mimes.add(new MIMEType(".jam", "application/x-jam"));
		mimes.add(new MIMEType(".jar", "application/java-archive"));
		mimes.add(new MIMEType(".jnlp", "application/x-java-jnlp-file"));
		mimes.add(new MIMEType(".jpe", "image/jpeg"));
		mimes.add(new MIMEType(".jpeg", "image/jpeg"));
		mimes.add(new MIMEType(".jpg", "image/jpeg"));
		mimes.add(new MIMEType(".jpz", "image/jpeg"));
		mimes.add(new MIMEType(".js", "application/x-javascript"));
		mimes.add(new MIMEType(".json", "application/json"));
		mimes.add(new MIMEType(".jwc", "application/jwc"));
		mimes.add(new MIMEType(".kjx", "application/x-kjx"));
		mimes.add(new MIMEType(".lak", "x-lml/x-lak"));
		mimes.add(new MIMEType(".latex", "application/x-latex" ));
		mimes.add(new MIMEType(".lcc", "application/fastman"));
		mimes.add(new MIMEType(".lcl", "application/x-digitalloca"));
		mimes.add(new MIMEType(".lcr", "application/x-digitalloca"));
		mimes.add(new MIMEType(".lgh", "application/lgh"));
		mimes.add(new MIMEType(".lha", "application/octet-stream"));
		mimes.add(new MIMEType(".lml", "x-lml/x-lml"));
		mimes.add(new MIMEType(".lmlpack", " x-lml/x-lmlpack"));
		mimes.add(new MIMEType(".lsf", "video/x-ms-asf"));
		mimes.add(new MIMEType(".lsx", "video/x-ms-asf"));
		mimes.add(new MIMEType(".lzh", "application/x-lzh"));
		mimes.add(new MIMEType(".m13", "application/x-msmediaview"));
		mimes.add(new MIMEType(".m14", "application/x-msmediaview"));
		mimes.add(new MIMEType(".m15", "audio/x-mod"));
		mimes.add(new MIMEType(".m3u", "audio/x-mpegurl"));
		mimes.add(new MIMEType(".m3url", "audio/x-mpegurl"));
		mimes.add(new MIMEType(".ma1", "audio/ma1"));
		mimes.add(new MIMEType(".ma2", "audio/ma2"));
		mimes.add(new MIMEType(".ma3", "audio/ma3"));
		mimes.add(new MIMEType(".ma5", "audio/ma5"));
		mimes.add(new MIMEType(".man", " application/x-troff-man"));
		mimes.add(new MIMEType(".map", "magnus-internal/imagemap"));
		mimes.add(new MIMEType(".mbd", "application/mbedlet"));
		mimes.add(new MIMEType(".mct", "application/x-mascot"));
		mimes.add(new MIMEType(".mdb", "application/x-msaccess"));
		mimes.add(new MIMEType(".mdz", "audio/x-mod"));
		mimes.add(new MIMEType(".me", "application/x-troff-me"));
		mimes.add(new MIMEType(".mel", "text/x-vmel"));
		mimes.add(new MIMEType(".mi", "application/x-mif"));
		mimes.add(new MIMEType(".mid", "audio/midi"));
		mimes.add(new MIMEType(".midi", "audio/midi"));
		mimes.add(new MIMEType(".mif", "application/x-mif"));
		mimes.add(new MIMEType(".mil", "image/x-cals"));
		mimes.add(new MIMEType(".mio", "audio/x-mio"));
		mimes.add(new MIMEType(".mmf", "application/x-skt-lbs"));
		mimes.add(new MIMEType(".mng", "video/x-mng"));
		mimes.add(new MIMEType(".mny", " application/x-msmoney"));
		mimes.add(new MIMEType(".moc", "application/x-mocha"));
		mimes.add(new MIMEType(".mocha", "application/x-mocha"));
		mimes.add(new MIMEType(".mod", "audio/x-mod"));
		mimes.add(new MIMEType(".mof", "application/x-yumekara"));
		mimes.add(new MIMEType(".mol", "chemical/x-mdl-molfile"));
		mimes.add(new MIMEType(".mop", "chemical/x-mopac-input"));
		mimes.add(new MIMEType(".mov", "video/quicktime"));
		mimes.add(new MIMEType(".movie", "video/x-sgi-movie"));
		mimes.add(new MIMEType(".mp2", "audio/x-mpeg"));
		mimes.add(new MIMEType(".mp3", "audio/x-mpeg"));
		mimes.add(new MIMEType(".mp4", "video/mp4"));
		mimes.add(new MIMEType(".mpc", "application/vnd.mpohun.certificate"));
		mimes.add(new MIMEType(".mpe", "video/mpeg"));
		mimes.add(new MIMEType(".mpeg", "video/mpeg"));
		mimes.add(new MIMEType(".mpg", "video/mpeg"));
		mimes.add(new MIMEType(".mpg4", "video/mp4"));
		mimes.add(new MIMEType(".mpga", "audio/mpeg"));
		mimes.add(new MIMEType(".mpn", "application/vnd.mophun.application"));
		mimes.add(new MIMEType(".mpp", "application/vnd.ms-project"));
		mimes.add(new MIMEType(".mps", "application/x-mapserver"));
		mimes.add(new MIMEType(".mrl", "text/x-mrml"));
		mimes.add(new MIMEType(".mrm", "application/x-mrm"));
		mimes.add(new MIMEType(".ms", "application/x-troff-ms"));
		mimes.add(new MIMEType(".mts", "application/metastream"));
		mimes.add(new MIMEType(".mtx", "application/metastream"));
		mimes.add(new MIMEType(".mtz", "application/metastream"));
		mimes.add(new MIMEType(".mzv", "application/metastream"));
		mimes.add(new MIMEType(".nar", "application/zip"));
		mimes.add(new MIMEType(".nbmp", "image/nbmp"));
		mimes.add(new MIMEType(".nc", "application/x-netcdf"));
		mimes.add(new MIMEType(".ndb", "x-lml/x-ndb"));
		mimes.add(new MIMEType(".ndwn", "application/ndwn"));
		mimes.add(new MIMEType(".nif", "application/x-nif"));
		mimes.add(new MIMEType(".nmz", "application/x-scream"));
		mimes.add(new MIMEType(".nokia-op-logo", "image/vnd.nok-oplogo-color"));
		mimes.add(new MIMEType(".npx", "application/x-netfpx"));
		mimes.add(new MIMEType(".nsnd", "audio/nsnd"));
		mimes.add(new MIMEType(".nva", "application/x-neva1"));
		mimes.add(new MIMEType(".oda", "application/oda"));
		mimes.add(new MIMEType(".oom", "application/x-AtlasMate-Plugin"));
		mimes.add(new MIMEType(".pac", "audio/x-pac"));
		mimes.add(new MIMEType(".pae", "audio/x-epac"));
		mimes.add(new MIMEType(".pan", "application/x-pan"));
		mimes.add(new MIMEType(".pbm", "image/x-portable-bitmap"));
		mimes.add(new MIMEType(".pcx", "image/x-pcx"));
		mimes.add(new MIMEType(".pda", "image/x-pda"));
		mimes.add(new MIMEType(".pdb", "chemical/x-pdb"));
		mimes.add(new MIMEType(".pdf", "application/pdf"));
		mimes.add(new MIMEType(".pfr", "application/font-tdpfr"));
		mimes.add(new MIMEType(".pgm", "image/x-portable-graymap"));
		mimes.add(new MIMEType(".pict", "image/x-pict"));
		mimes.add(new MIMEType(".pm", "application/x-perl"));
		mimes.add(new MIMEType(".pmd", "application/x-pmd"));
		mimes.add(new MIMEType(".png", "image/png"));
		mimes.add(new MIMEType(".pnm", "image/x-portable-anymap"));
		mimes.add(new MIMEType(".pnz", "image/png"));
		mimes.add(new MIMEType(".pot", "application/vnd.ms-powerpoint"));
		mimes.add(new MIMEType(".ppm", "image/x-portable-pixmap"));
		mimes.add(new MIMEType(".pps", "application/vnd.ms-powerpoint"));
		mimes.add(new MIMEType(".ppt", "application/vnd.ms-powerpoint"));
		mimes.add(new MIMEType(".pqf", "application/x-cprplayer"));
		mimes.add(new MIMEType(".pqi", "application/cprplayer"));
		mimes.add(new MIMEType(".prc", "application/x-prc"));
		mimes.add(new MIMEType(".proxy", "application/x-ns-proxy-autoconfig"));
		mimes.add(new MIMEType(".ps", "application/postscript"));
		mimes.add(new MIMEType(".ptlk", "application/listenup"));
		mimes.add(new MIMEType(".pub", "application/x-mspublisher"));
		mimes.add(new MIMEType(".pvx", "video/x-pv-pvx"));
		mimes.add(new MIMEType(".qcp", "audio/vnd.qcelp"));
		mimes.add(new MIMEType(".qt", "video/quicktime"));
		mimes.add(new MIMEType(".qti", "image/x-quicktime"));
		mimes.add(new MIMEType(".qtif", "image/x-quicktime"));
		mimes.add(new MIMEType(".r3t", "text/vnd.rn-realtext3d"));
		mimes.add(new MIMEType(".ra", "audio/x-pn-realaudio"));
		mimes.add(new MIMEType(".ram", "audio/x-pn-realaudio"));
		mimes.add(new MIMEType(".rar", "application/octet-stream"));
		mimes.add(new MIMEType(".ras", " image/x-cmu-raster"));
		mimes.add(new MIMEType(".rdf", "application/rdf+xml"));
		mimes.add(new MIMEType(".rf", "image/vnd.rn-realflash"));
		mimes.add(new MIMEType(".rgb", "image/x-rgb"));
		mimes.add(new MIMEType(".rlf", "application/x-richlink"));
		mimes.add(new MIMEType(".rm", "audio/x-pn-realaudio"));
		mimes.add(new MIMEType(".rmf", "audio/x-rmf"));
		mimes.add(new MIMEType(".rmm", "audio/x-pn-realaudio"));
		mimes.add(new MIMEType(".rmvb", " audio/x-pn-realaudio"));
		mimes.add(new MIMEType(".rnx", "application/vnd.rn-realplayer"));
		mimes.add(new MIMEType(".roff", "application/x-troff"));
		mimes.add(new MIMEType(".rp", "image/vnd.rn-realpix"));
		mimes.add(new MIMEType(".rpm", "audio/x-pn-realaudio-plugin"));
		mimes.add(new MIMEType(".rt", "text/vnd.rn-realtext"));
		mimes.add(new MIMEType(".rte", " x-lml/x-gps"));
		mimes.add(new MIMEType(".rtf", "application/rtf"));
		mimes.add(new MIMEType(".rtg", "application/metastream"));
		mimes.add(new MIMEType(".rtx", "text/richtext"));
		mimes.add(new MIMEType(".rv", "video/vnd.rn-realvideo"));
		mimes.add(new MIMEType(".rwc", "application/x-rogerwilco"));
		mimes.add(new MIMEType(".s3m", "audio/x-mod"));
		mimes.add(new MIMEType(".s3z", "audio/x-mod"));
		mimes.add(new MIMEType(".sca", "application/x-supercard"));
		mimes.add(new MIMEType(".scd", "application/x-msschedule"));
		mimes.add(new MIMEType(".sdf", "application/e-score"));
		mimes.add(new MIMEType(".sea", "application/x-stuffit"));
		mimes.add(new MIMEType(".sgm", "text/x-sgml"));
		mimes.add(new MIMEType(".sgml", "text/x-sgml"));
		mimes.add(new MIMEType(".sh", "application/x-sh"));
		mimes.add(new MIMEType(".shar", "application/x-shar"));
		mimes.add(new MIMEType(".shtml", "magnus-internal/parsed-html"));
		mimes.add(new MIMEType(".shw", "application/presentations"));
		mimes.add(new MIMEType(".si6", "image/si6"));
		mimes.add(new MIMEType(".si7", "image/vnd.stiwap.sis"));
		mimes.add(new MIMEType(".si9", "image/vnd.lgtwap.sis"));
		mimes.add(new MIMEType(".sis", "application/vnd.symbian.install"));
		mimes.add(new MIMEType(".sit", "application/x-stuffit"));
		mimes.add(new MIMEType(".skd", "application/x-Koan"));
		mimes.add(new MIMEType(".skm", "application/x-Koan"));
		mimes.add(new MIMEType(".skp", "application/x-Koan"));
		mimes.add(new MIMEType(".skt", "application/x-Koan"));
		mimes.add(new MIMEType(".slc", "application/x-salsa"));
		mimes.add(new MIMEType(".smd", "audio/x-smd"));
		mimes.add(new MIMEType(".smi", "application/smil"));
		mimes.add(new MIMEType(".smil", "application/smil"));
		mimes.add(new MIMEType(".smp", "application/studiom"));
		mimes.add(new MIMEType(".smz", "audio/x-smd"));
		mimes.add(new MIMEType(".snd", "audio/basic"));
		mimes.add(new MIMEType(".spc", "text/x-speech"));
		mimes.add(new MIMEType(".spl", "application/futuresplash"));
		mimes.add(new MIMEType(".spr", "application/x-sprite"));
		mimes.add(new MIMEType(".sprite", "application/x-sprite"));
		mimes.add(new MIMEType(".sdp", "application/sdp"));
		mimes.add(new MIMEType(".spt", "application/x-spt"));
		mimes.add(new MIMEType(".src", "application/x-wais-source"));
		mimes.add(new MIMEType(".stk", "application/hyperstudio"));
		mimes.add(new MIMEType(".stm", "audio/x-mod"));
		mimes.add(new MIMEType(".sv4cpio", "application/x-sv4cpio"));
		mimes.add(new MIMEType(".sv4crc", "application/x-sv4crc"));
		mimes.add(new MIMEType(".svf", "image/vnd"));
		mimes.add(new MIMEType(".svg", "image/svg-xml"));
		mimes.add(new MIMEType(".svh", "image/svh"));
		mimes.add(new MIMEType(".svr", "x-world/x-svr"));
		mimes.add(new MIMEType(".swf", "application/x-shockwave-flash"));
		mimes.add(new MIMEType(".swfl", "application/x-shockwave-flash"));
		mimes.add(new MIMEType(".t", "application/x-troff"));
		mimes.add(new MIMEType(".tad", "application/octet-stream"));
		mimes.add(new MIMEType(".talk", "text/x-speech"));
		mimes.add(new MIMEType(".tar", "application/x-tar"));
		mimes.add(new MIMEType(".taz", "application/x-tar"));
		mimes.add(new MIMEType(".tbp", "application/x-timbuktu"));
		mimes.add(new MIMEType(".tbt", "application/x-timbuktu"));
		mimes.add(new MIMEType(".tcl", "application/x-tcl"));
		mimes.add(new MIMEType(".tex", "application/x-tex"));
		mimes.add(new MIMEType(".texi", "application/x-texinfo"));
		mimes.add(new MIMEType(".texinfo", "application/x-texinfo"));
		mimes.add(new MIMEType(".tgz", "application/x-tar"));
		mimes.add(new MIMEType(".thm", "application/vnd.eri.thm"));
		mimes.add(new MIMEType(".tif", "image/tiff"));
		mimes.add(new MIMEType(".tiff", "image/tiff"));
		mimes.add(new MIMEType(".tki", "application/x-tkined"));
		mimes.add(new MIMEType(".tkined", "application/x-tkined"));
		mimes.add(new MIMEType(".toc", "application/toc"));
		mimes.add(new MIMEType(".toy", "image/toy"));
		mimes.add(new MIMEType(".tr", "application/x-troff"));
		mimes.add(new MIMEType(".trk", "x-lml/x-gps"));
		mimes.add(new MIMEType(".trm", "application/x-msterminal"));
		mimes.add(new MIMEType(".tsi", "audio/tsplayer"));
		mimes.add(new MIMEType(".tsp", "application/dsptype"));
		mimes.add(new MIMEType(".tsv", "text/tab-separated-values"));
		mimes.add(new MIMEType(".ttf", "application/octet-stream"));
		mimes.add(new MIMEType(".ttz", "application/t-time"));
		mimes.add(new MIMEType(".txt", "text/plain"));
		mimes.add(new MIMEType(".ult", "audio/x-mod"));
		mimes.add(new MIMEType(".ustar", "application/x-ustar"));
		mimes.add(new MIMEType(".uu", "application/x-uuencode"));
		mimes.add(new MIMEType(".uue", "application/x-uuencode"));
		mimes.add(new MIMEType(".vcd", "application/x-cdlink"));
		mimes.add(new MIMEType(".vcf", "text/x-vcard"));
		mimes.add(new MIMEType(".vdo", "video/vdo"));
		mimes.add(new MIMEType(".vib", "audio/vib"));
		mimes.add(new MIMEType(".viv", "video/vivo"));
		mimes.add(new MIMEType(".vivo", "video/vivo"));
		mimes.add(new MIMEType(".vmd", "application/vocaltec-media-desc"));
		mimes.add(new MIMEType(".vmf", "application/vocaltec-media-file"));
		mimes.add(new MIMEType(".vmi", "application/x-dreamcast-vms-info"));
		mimes.add(new MIMEType(".vms", "application/x-dreamcast-vms"));
		mimes.add(new MIMEType(".vox", "audio/voxware"));
		mimes.add(new MIMEType(".vqe", "audio/x-twinvq-plugin"));
		mimes.add(new MIMEType(".vqf", "audio/x-twinvq"));
		mimes.add(new MIMEType(".vql", "audio/x-twinvq"));
		mimes.add(new MIMEType(".vre", "x-world/x-vream"));
		mimes.add(new MIMEType(".vrml", "x-world/x-vrml"));
		mimes.add(new MIMEType(".vrt", "x-world/x-vrt"));
		mimes.add(new MIMEType(".vrw", "x-world/x-vream"));
		mimes.add(new MIMEType(".vts", "workbook/formulaone"));
		mimes.add(new MIMEType(".wav", "audio/x-wav"));
		mimes.add(new MIMEType(".wax", "audio/x-ms-wax"));
		mimes.add(new MIMEType(".wbmp", "image/vnd.wap.wbmp"));
		mimes.add(new MIMEType(".web", "application/vnd.xara"));
		mimes.add(new MIMEType(".wi", "image/wavelet"));
		mimes.add(new MIMEType(".wis", "application/x-InstallShield"));
		mimes.add(new MIMEType(".wm", "video/x-ms-wm"));
		mimes.add(new MIMEType(".wma", "audio/x-ms-wma"));
		mimes.add(new MIMEType(".wmd", "application/x-ms-wmd"));
		mimes.add(new MIMEType(".wmf", "application/x-msmetafile"));
		mimes.add(new MIMEType(".wml", "text/vnd.wap.wml"));
		mimes.add(new MIMEType(".wmlc", "application/vnd.wap.wmlc"));
		mimes.add(new MIMEType(".wmls", "text/vnd.wap.wmlscript"));
		mimes.add(new MIMEType(".wmlsc", "application/vnd.wap.wmlscriptc"));
		mimes.add(new MIMEType(".wmlscript", "text/vnd.wap.wmlscript"));
		mimes.add(new MIMEType(".wmv", "video/x-ms-wmv"));
		mimes.add(new MIMEType(".wmx", "video/x-ms-wmx"));
		mimes.add(new MIMEType(".wmz", "application/x-ms-wmz"));
		mimes.add(new MIMEType(".wpng", "image/x-up-wpng"));
		mimes.add(new MIMEType(".wpt", "x-lml/x-gps"));
		mimes.add(new MIMEType(".wri", "application/x-mswrite"));
		mimes.add(new MIMEType(".wrl", "x-world/x-vrml"));
		mimes.add(new MIMEType(".wrz", "x-world/x-vrml"));
		mimes.add(new MIMEType(".ws", "text/vnd.wap.wmlscript"));
		mimes.add(new MIMEType(".wsc", "application/vnd.wap.wmlscriptc"));
		mimes.add(new MIMEType(".wv", "video/wavelet"));
		mimes.add(new MIMEType(".wvx", "video/x-ms-wvx"));
		mimes.add(new MIMEType(".wxl", "application/x-wxl"));
    	mimes.add(new MIMEType(".x-gzip", "application/x-gzip"));
		mimes.add(new MIMEType(".xar", "application/vnd.xara"));
		mimes.add(new MIMEType(".xbm", "image/x-xbitmap"));
		mimes.add(new MIMEType(".xdm", "application/x-xdma"));
		mimes.add(new MIMEType(".xdma", "application/x-xdma"));
		mimes.add(new MIMEType(".xdw", "application/vnd.fujixerox.docuworks"));
		mimes.add(new MIMEType(".xht", "application/xhtml+xml"));
		mimes.add(new MIMEType(".xhtm", "application/xhtml+xml"));
		mimes.add(new MIMEType(".xhtml", "application/xhtml+xml"));
		mimes.add(new MIMEType(".xla", "application/vnd.ms-excel"));
		mimes.add(new MIMEType(".xlc", "application/vnd.ms-excel"));
		mimes.add(new MIMEType(".xll", "application/x-excel"));
		mimes.add(new MIMEType(".xlm", "application/vnd.ms-excel"));
		mimes.add(new MIMEType(".xls", "application/vnd.ms-excel"));
		mimes.add(new MIMEType(".xlt", "application/vnd.ms-excel"));
		mimes.add(new MIMEType(".xlw", "application/vnd.ms-excel"));
		mimes.add(new MIMEType(".xm", "audio/x-mod"));
		mimes.add(new MIMEType(".xml", "text/xml"));
		mimes.add(new MIMEType(".xmz", "audio/x-mod"));
		mimes.add(new MIMEType(".xpi", "application/x-xpinstall"));
		mimes.add(new MIMEType(".xpm", "image/x-xpixmap"));
		mimes.add(new MIMEType(".xsit", "text/xml"));
		mimes.add(new MIMEType(".xsl", "text/xml"));
		mimes.add(new MIMEType(".xul", "text/xul"));
		mimes.add(new MIMEType(".xwd", "image/x-xwindowdump"));
		mimes.add(new MIMEType(".xyz", "chemical/x-pdb"));
		mimes.add(new MIMEType(".yz1", "application/x-yz1"));
		mimes.add(new MIMEType(".z", "application/x-compress"));
		mimes.add(new MIMEType(".zac", "application/x-zaurus-zac"));
		mimes.add(new MIMEType(".zip", "application/zip"));
	}
	/**
	 * 依据文件扩展名（包容点号，如“.html”）获取MIME类型，如果找不到，返回null
	 * @param fileExtension：不把持文件名，仅包容扩展名。
	 * 可以使用FileUtils提取文件扩展名
	 * @return
	 */
	public static String getMIME(String fileExtension) {
		if(StringUtils.isNullOrEmpty(fileExtension)){
			return null;
		}
		int index=mimes.indexOf(new MIMEType(fileExtension, ""));
		if(index!=-1){
			return mimes.get(index).getMIME();
		}
		return null;
	}
	/**
	 * 依据MIME类型名，获取它的文件扩展名（包容点号，如“.html”）
	 * @param MIME
	 * @return
	 */
	public static String getFileExtension(String MIME) {
		if(StringUtils.isNullOrEmpty(MIME)){
			return null;
		}
		
		for (MIMEType obj : mimes) {
			if(obj.getMIME().equals(MIME)){
				return obj.getFileExtension();
			}
		}
		return null;
	}
	
}
