/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devseed_fiveinarow_ChessKernel */

#ifndef _Included_com_devseed_fiveinarow_ChessKernel
#define _Included_com_devseed_fiveinarow_ChessKernel
#ifdef __cplusplus
extern "C" {
#endif
#undef com_devseed_fiveinarow_ChessKernel_white
#define com_devseed_fiveinarow_ChessKernel_white 72L
#undef com_devseed_fiveinarow_ChessKernel_black
#define com_devseed_fiveinarow_ChessKernel_black 42L
#undef com_devseed_fiveinarow_ChessKernel_empty
#define com_devseed_fiveinarow_ChessKernel_empty 48L
/*
 * Class:     com_devseed_fiveinarow_ChessKernel
 * Method:    JudgeWin
 * Signature: ([[CII)C
 */
JNIEXPORT jchar JNICALL Java_com_devseed_fiveinarow_ChessKernel_JudgeWin
  (JNIEnv *, jobject, jobjectArray, jint, jint);

/*
 * Class:     com_devseed_fiveinarow_ChessKernel
 * Method:    AI_kuon_pos
 * Signature: ([[CIIC)Lcom/devseed/fiveinarow/ChessKernel/StepNode;
 */
JNIEXPORT jobject JNICALL Java_com_devseed_fiveinarow_ChessKernel_AI_1kuon_1pos
  (JNIEnv *, jobject, jobjectArray, jint, jint, jchar);

/*
 * Class:     com_devseed_fiveinarow_ChessKernel
 * Method:    AI_kuon_gametree
 * Signature: ([[CIIC)Lcom/devseed/fiveinarow/ChessKernel/StepNode;
 */
JNIEXPORT jobject JNICALL Java_com_devseed_fiveinarow_ChessKernel_AI_1kuon_1gametree
  (JNIEnv *, jobject, jobjectArray, jint, jint, jchar);

#ifdef __cplusplus
}
#endif
#endif
