/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_devseed_fiveinarow_ChessKernel_ChessStep */

#ifndef _Included_com_devseed_fiveinarow_ChessKernel_ChessStep
#define _Included_com_devseed_fiveinarow_ChessKernel_ChessStep
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
